### ISSUE TITLE
Mistype on bot response

### ISSUE THREAD

**Issue by KY64** [Verdia/Chatbot-Keras#1]
Hi, I found a mistype in the bot response.

https://github.com/Verdia/Chatbot-Keras/blob/47dd0dc1527faa2b8fd3aa2a75c21c22b7eae8ec/dataset.json#L21

"_**I.m** Joana, your bot assistant_" can be replaced with "_**I'm** Joana, your bot assistant_"

**Comment by vianvardy** [comment]
ahh forgot about that, thanks for remind me
